bot:
  url: https://api.telegram.org/bot
  name: FirstTestingBot
  chatId: -1001238385079
  token: 1574801869:AAErCVUSFkL7aAxyvNNbDAsLy3vUov-yGs0

server:
  port: 80

spring.datasource.url: jdbc:mysql://localhost:3306/ea_pattern
spring.datasource.username: root
spring.datasource.password: hWN-h2z-aPE-8dQ
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto: update
spring.jpa.show-sql: false
spring.jpa.properties.hibernate.format_sql: false